#pragma once
#include <ntifs.h>

#define IO_GET_CLIENTADDRESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x480, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_READ_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x481, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_WRITE_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x482, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

NTSTATUS IoControl(PDEVICE_OBJECT deviceObject, PIRP irp);

NTSTATUS CloseCall(PDEVICE_OBJECT deviceObject, PIRP irp);

NTSTATUS CreateCall(PDEVICE_OBJECT deviceObject, PIRP irp);

extern NTKERNELAPI PVOID PsGetProcessSectionBaseAddress(
	IN PEPROCESS		Process
);

#pragma pack(push, 8)
typedef struct _KERNEL_READ_REQUEST
{
	ULONGLONG ProcessId;
	ULONGLONG Address;
	DWORD64 pBuff;
	ULONGLONG Size;

} KERNEL_READ_REQUEST, * PKERNEL_READ_REQUEST;
#pragma pack(pop)

#pragma pack(push, 8)
typedef struct _KERNEL_WRITE_REQUEST
{
	ULONGLONG ProcessId;
	ULONGLONG Address;
	DWORD64 pBuff;
	ULONGLONG Size;

} KERNEL_WRITE_REQUEST, * PKERNEL_WRITE_REQUEST;
#pragma pack(pop)